### ISSUE TITLE
TypeError: Cannot destructure property `title` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by washedsamo** [ericz99/supreme-monitor#2]
Hi!

I tried to run your monitor on my private server, it worked for like a 30 seconds 

> yarn run v1.13.0
$ node index.js
[23:34:52.549] [Supreme Monitor V2] [+] Initial check done!
[23:34:52.553] [Supreme Monitor V2] [#] Poll Time: 2000 MS
[23:34:52.554] [Supreme Monitor V2] [?] Running for restock!

but it crashed after 20-30 seconds for some reason, my config.json is correct and i didn't touch the code so.. here's the error message

<img width="652" alt="Screenshot 2019-03-21 at 23 48 26" src="https://user-images.githubusercontent.com/26344980/54789752-d9a4a580-4c33-11e9-8e15-35408406104c.png">

**Comment by ericz99** [comment]
hey, is your locale en_US or en_GB?

**Comment by ericz99** [comment]
need to know which locale you set to, in order to fix issue.

**Comment by washedsamo** [comment]
it's en_GB

**Comment by ericz99** [comment]
ook ok, I got some EU proxies, going to test it now.

**Comment by ericz99** [comment]
hey, dude i have another version coming out very soon that will support supreme UK, this version doesn't unfortunately.. Sorry for the inconvenience!

**Comment by riccardoravelli** [comment]
oh ok, let me know for the monitor and thx for the support, big up 🤙🏻

Inviato da iPhone
