### ISSUE TITLE
TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by ilumik** [ericz99/supreme-monitor#4]
![Screenshot_25](https://user-images.githubusercontent.com/48921175/55196428-999f6e80-51af-11e9-9e5c-49857ec28251.png)
every time i start the bot this error comes up, how to fix it?

**Comment by alecjb12** [comment]
I have the same error

**Comment by ericz99** [comment]
yo, ill fix it by tonight

**Comment by alecjb12** [comment]
You seem pretty good with this stuff. Would you be interested in being a
dev for my discord group. We need someone like you apart of our team.

If you can, join up and we can talk business
https://discord.gg/mWyHu98

My username is Alecjb12

**Comment by washedsamo** [comment]
you literally charge people for monitor which you didn't even develop and is available for free on github? weird

<img width="421" alt="Screenshot 2019-04-03 at 21 23 27" src="https://user-images.githubusercontent.com/26344980/55507022-1e2e3900-5657-11e9-8d36-c335244ae908.png">

**Comment by ericz99** [comment]
huh?

**Comment by ericz99** [comment]
I don't sell stuff on discord, and that's not me...

**Comment by washedsamo** [comment]
i meant @alecjb12

**Comment by ericz99** [comment]
oh xD

**Comment by alecjb12** [comment]
Where did this guy come from! Lol no I don’t charge for the monitor, I
charge 5 to Access all that because of my paid staff and hosting the
monitors on a fast VPS with good proxies costs me over $150 a month.

**Comment by alecjb12** [comment]
Anyways, @ericz99 if you are interested in being a dev, join up and dm me

**Comment by ericz99** [comment]
lads, I added error checking, the reason why you receive that error is because the request is null, therefore i assumed you are banned. This never happened to me before.. If you are using a server, its likely to be banned by supreme because "majority" of "cloud" server is blocked by supreme. You can use proxies to get around that..
