### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by iamjunmo** [ericz99/supreme-monitor#6]
Hi!
I really appreciate for your supreme monitor.
how do i put multiple proxies one config.json?
"proxy": [12.23.456.45:7777:asd:asd],[proxy],[proxy].
or
"proxy": "proxies","proxy" ?

Thank you.

**Comment by ericz99** [comment]
The second way. Proxy: [“12.12.12.12:123”,  ...], like this.

**Comment by iamjunmo** [comment]
> The second way. Proxy: [“12.12.12.12:123”, ...], like this.

finally, it works!! I really appreciate it

**Comment by ericz99** [comment]
Np. Gonna close issue now. If you have other issue feel free to open.
