### ISSUE TITLE
Parent of null issue

### ISSUE THREAD

**Issue by alecjb12** [ericz99/supreme-monitor#8]
![image](https://user-images.githubusercontent.com/48979484/56937773-18a8ff00-6aee-11e9-97de-e7b8476a2e84.png)

**Comment by ericz99** [comment]
you probably temp ban..

**Comment by alecjb12** [comment]
I dont think so, I used proxies

**Comment by ericz99** [comment]
according to that screenshot, you are using 0 proxy. So i assumed that's the reason why you are getting that error. It couldn't parse any data. Therefore you are temp ban.

**Comment by alecjb12** [comment]
I used a dedicated proxy after I sent that email. Same result.

**Comment by alecjb12** [comment]
I also tried to use backconnect rotating proxies. Same error
